apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.auth.secretName }}
  labels:
    app: {{ include "redis-sentinel.fullname" . }}
    component: redis
data:
  password: {{ include "redis.adminPassword" . }}
type: Opaque
