{{- $aclFileContent := "include /redis/redis.conf" }}
{{- range .Values.redis.acl.users }}
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secretName) }}
{{- $userPassword := "" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    {{- include "redis-sentinel.labels" $ | nindent 4 }}
type: Opaque
data:
  username: {{ .username | b64enc | quote }}
{{- if not $secret}}
{{ $userPassword = randAlphaNum 12 }}
{{- else }}
{{ $userPassword = $secret.data.password | b64dec }}
{{- end }}
  password: {{ $userPassword | b64enc | quote}}
{{ $aclFileContent = printf "%s\nuser %s %s %s on >%s" $aclFileContent .username .permissions .keyPattern $userPassword }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.acl.secretName }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.redis.acl.configFile }}: {{ $aclFileContent | b64enc }}